### PR TITLE
upgrade to vue2-leaflet v1.0.0

### PR DESCRIPTION
**Pull request by naderio**

### CODE REVIEW

**Comment by naderio** [comment]
suffers from an issue where markers do not reappear on second zoom with following stacktrace

```
vue.runtime.esm.js?a427:587 [Vue warn]: Error in callback for watcher "latLng": "TypeError: Cannot read property '_zoom' of undefined"

found in

---> <LMarker>
       <VMarkerCluster> at /opt/Workspace/contrib/vue2-leaflet-markercluster/Vue2LeafletMarkercluster.vue
         <LMap>
           <Example> at /opt/Workspace/contrib/vue2-leaflet-markercluster/example.vue
             <Root>

TypeError: Cannot read property '_zoom' of undefined
    at NewClass.addLayer (leaflet.markercluster-src.js?7b9c:135)
    at NewClass._moveChild (leaflet.markercluster-src.js?7b9c:718)
    at NewClass._childMarkerMoved (leaflet.markercluster-src.js?7b9c:705)
    at NewClass.fire (leaflet-src.js?6144:593)
    at NewClass.setLatLng (leaflet-src.js?6144:7405)
    at VueComponent.n.(:4000/anonymous function).custom.setOptions.t.$watch.deep (webpack-internal:///80:1:2003)
    at Watcher.run (vue.runtime.esm.js?a427:3229)
    at flushSchedulerQueue (vue.runtime.esm.js?a427:2977)
    at Array.eval (vue.runtime.esm.js?a427:1833)
    at flushCallbacks (vue.runtime.esm.js?a427:1754)
```

**Comment by naderio** [comment]
issue appears to be caused by following code on `mounted` in `LMarker.vue` from `vue-leaflet` package, in combination with `animate` option

```javascript
    this.mapObject.on('move', (ev) => {
      if (Array.isArray(this.latLng)) {
        this.latLng[0] = ev.latlng.lat;
        this.latLng[1] = ev.latlng.lng;
      } else {
        this.latLng.lat = ev.latlng.lat;
        this.latLng.lng = ev.latlng.lng;
      }
    });
```
setting `animate` to `false` seems to resolve the issue

**Comment by naderio** [comment]
should be fixed; waiting for https://github.com/KoRiGaN/Vue2Leaflet/pull/148  to be merged & published

**Comment by jperelli** [comment]
Awesome! ping me here again when KoRiGaN/Vue2Leaflet#148 is merged so we can adjust the versions and merge this PR. Thanks!

**Comment by sangdth** [comment]
Thank you for your works @naderio and please ping me too with any progress.

**Comment by fdenzer** [comment]
@jperelli pinging you, as merge has occured: A new release, version 1.0.2 is out!

**Comment by naderio** [comment]
@jperelli should be ready to merge

**Comment by jperelli** [comment]
Awesome! I'll test this later today and hopefully will be merged and released today. Thank you very much for your contribution @naderio !

**Comment by jperelli** [comment]
sorry for the delay guys, I merged it and I'm now publishing to npm version 2.0.0

**Pull request merged**
